### PR TITLE
Filter pull requests by the name of their branches

### PR DESCRIPTION
**Pull request by takahi-i**
Ref #105

### CODE REVIEW

**Comment by mizzy** [comment]
I'm worrying about two points.

1. Config parameter name `filter` is a bit confusing. I can't tell it is pointing branch name by the parameter name.
2. `filepath.Match` uses *wild card* to check matching, not regular expression.

**Comment by takahi-i** [comment]
Thank you very much for the comment!

**Comment by sawanoboly** [comment]
regular expression :+1:

**Comment by mizzy** [comment]
LGTM :+1:

**Pull request merged**
